"""
You are given two strings, str_1 and str_2, where str_2 is generated by randomly shuffling str_1 and then adding one letter at a random position.

Write a function that returns the letter that was added to str_2.

Examples:

    solution(str_1 = "bcde", str_2 = "bdcef") -> "f"
    solution(str_1 = "", str_2 = "z") -> "z"
    solution(str_1 = "b", str_2 = "bb") -> "b"
    solution(str_1 = "bf", str_2 = "bfb") -> "b"

Notes:

    str_1 and str_2 both consist of only lowercase alpha characters.

    [execution time limit] 4 seconds (py3)

    [input] string str_1

    [input] string str_2

    [output] string

https://app.codesignal.com/solutions/F7YLwBEWuG5LeZpRa?accessToken=riSN79DwWmRmwFk5H-ekfqqLEKxN43Gdn94jai6Ksf
"""

def solution(str_1, str_2):
    first = sorted(str_1)
    first.append(' ')
    second = sorted(str_2)
    
    j = 0
    for x in second:
        if x != first[j]:
            return x
        j += 1